version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cp4-java-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8282:8282"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521:XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
      - SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD=60000
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=XE
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -L system/oracle@//localhost:1521/XE <<< 'SELECT 1 FROM DUAL;' | grep -q '1'"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s
    restart: unless-stopped

volumes:
  oracle-data:

networks:
  app-network:
    driver: bridge